//In-Page Alerts
export const EMAIL_CONFIRM = "EMAIL_CONFIRM";

export const MAKE_GROUP_PUBLIC = "MAKE_GROUP_PUBLIC"

export const MAKE_USER_VISIBLE = "MAKE_USER_VISIBLE"

export const FETCH_SINGLE_GROUP_FAILED = "FETCH_SINGLE_GROUP_FAILED";

export const INVITATION_LINK_PROBLEM = "INVITATION_LINK_PROBLEM";

export const INVITATION_LINK_ALREADY_IN_GROUP = "INVITATION_LINK_ALREADY_IN_GROUP";


//Snackbar
export const COPY_LINK_SUCCESS = "COPY_LINK_SUCCESS";
export const SENT_INVITATION_LINK_SUCCESS = "SENT_INVITATION_LINK_SUCCESS";
export const SENT_INVITATION_LINK_FAILED = "SENT_INVITATION_LINK_FAILED";

export const COPY_NEWS_LINK = "COPY_NEWS_LINK";

export const TOGGLE_TASK_FAILED = "TOGGLE_TASK_FAILED";