export const EMAIL_CONFIRM = "EMAIL_CONFIRM";

export const MAKE_GROUP_PUBLIC = "MAKE_GROUP_PUBLIC"

export const FETCH_SINGLE_GROUP_ERROR = "FETCH_SINGLE_GROUP_ERROR";

export const INVITATION_LINK_PROBLEM = "INVITATION_LINK_PROBLEM";

export const INVITATION_LINK_ALREADY_IN_GROUP = "INVITATION_LINK_ALREADY_IN_GROUP";