export const GOOGLE_SIGN_UP_START = "GOOGLE_SIGN_UP_START";
export const GOOGLE_SIGN_UP_SUCCESS = "GOOGLE_SIGN_UP_SUCCESS";
export const GOOGLE_SIGN_UP_FAILED = "GOOGLE_SIGN_UP_FAILED";

export const STANDARD_SIGN_UP_START = "STANDARD_SIGN_UP_START";
export const STANDARD_SIGN_UP_SUCCESS = "STANDARD_SIGN_UP_SUCCESS";
export const STANDARD_SIGN_UP_FAILED = "STANDARD_SIGN_UP_FAILED";

export const SIGN_OUT_START = "SIGN_OUT_START";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

export const LOG_IN_START = "LOG_IN_START";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILED = "LOG_IN_FAILED";

export const SEND_VERIFICATION_EMAIL_START = "SEND_VERIFICATION_EMAIL_START";
export const SEND_VERIFICATION_EMAIL_SUCCESS =
  "SEND_VERIFICATION_EMAIL_SUCCESS";
export const SEND_VERIFICATION_EMAIL_FAILED = "SEND_VERIFICATION_EMAIL_FAILED";

export const AUTH_CHECK_START = "AUTH_CHECK_START";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
export const AUTH_CHECK_FAILED = "AUTH_CHECK_FAILED";

export const FETCH_USER_DATA_START = "FETCH_USER_DATA_START";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILED = "FETCH_USER_DATA_FAILED";

export const POST_USER_DATA_START = "POST_USER_DATA_START";
export const POST_USER_DATA_SUCCESS = "POST_USER_DATA_SUCCESS";
export const POST_USER_DATA_FAILED = "POST_USER_DATA_FAILED";
