//auth
export const GOOGLE_SIGN_UP_START = "GOOGLE_SIGN_UP_START";
export const GOOGLE_SIGN_UP_SUCCESS = "GOOGLE_SIGN_UP_SUCCESS";
export const GOOGLE_SIGN_UP_FAILED = "GOOGLE_SIGN_UP_FAILED";

export const STANDARD_SIGN_UP_START = "STANDARD_SIGN_UP_START";
export const STANDARD_SIGN_UP_SUCCESS = "STANDARD_SIGN_UP_SUCCESS";
export const STANDARD_SIGN_UP_FAILED = "STANDARD_SIGN_UP_FAILED";

export const SIGN_OUT_START = "SIGN_OUT_START";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

export const LOG_IN_START = "LOG_IN_START";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILED = "LOG_IN_FAILED";

export const SEND_VERIFICATION_EMAIL_START = "SEND_VERIFICATION_EMAIL_START";
export const SEND_VERIFICATION_EMAIL_SUCCESS ="SEND_VERIFICATION_EMAIL_SUCCESS";
export const SEND_VERIFICATION_EMAIL_FAILED = "SEND_VERIFICATION_EMAIL_FAILED";

export const AUTH_CHECK_START = "AUTH_CHECK_START";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
export const AUTH_CHECK_FAILED = "AUTH_CHECK_FAILED";

export const SEND_PASSWORD_RESET_EMAIL_START = "SEND_PASSWORD_RESET_EMAIL_START";
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS = "SEND_PASSWORD_RESET_EMAIL_SUCCESS";
export const SEND_PASSWORD_RESET_EMAIL_FAILED = "SEND_PASSWORD_RESET_EMAIL_FAILED";

export const SIGN_IN_PROVIDER_START = "SIGN_IN_PROVIDER_START";
export const SIGN_IN_PROVIDER_SUCCESS = "SIGN_IN_PROVIDER_SUCCESS";
export const SIGN_IN_PROVIDER_FAILED = "SIGN_IN_PROVIDER_FAILED";

//userData / groupData

export const UPDATE_GROUP_LAST_ACTIVITY = "UPDATE_GROUP_LAST_ACTIVITY";

export const UPDATE_PUBLIC_DASHBOARD_SUCCESS = "UPDATE_PUBLIC_DASHBOARD_SUCCESS";
export const UPDATE_PUBLIC_DASHBOARD_FAILED = "UPDATE_PUBLIC_DASHBOARD_FAILED";

export const FETCH_INITIAL_DATA_START = "FETCH_INITIAL_DATA_START";
export const FETCH_INITIAL_DATA_SUCCESS = "FETCH_INITIAL_DATA_SUCCESS";
export const FETCH_INITIAL_DATA_FAILED = "FETCH_INITIAL_DATA_FAILED";

export const FETCH_GROUP_DATA_START = "FETCH_GROUP_DATA_START";
export const FETCH_GROUP_DATA_SUCCESS = "FETCH_GROUP_DATA_SUCCESS";
export const FETCH_GROUP_DATA_FAILED = "FETCH_GROUP_DATA_FAILED";

export const FETCH_NEWS_START = "FETCH_NEWS_START";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILED = "FETCH_NEWS_FAILED";

export const FETCH_USER_PROFILE_START = "FETCH_USER_PROFILE_START";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILED = "FETCH_USER_PROFILE_FAILED";

export const CLEAR_DASHBOARD_DATA_START = "CLEAR_DASHBOARD_DATA_START";
export const CLEAR_DASHBOARD_DATA_SUCCESS = "CLEAR_DASHBOARD_DATA_SUCCESS";
export const CLEAR_DASHBOARD_DATA_FAILED = "CLEAR_DASHBOARD_DATA_FAILED";
export const CLEAR_DASHBOARD_DATA_LOCAL = "CLEAR_DASHBOARD_DATA_LOCAL";

export const FETCH_SINGLE_GROUP_START = "FETCH_SINGLE_GROUP_START";
export const FETCH_SINGLE_GROUP_SUCCESS = "FETCH_SINGLE_GROUP_SUCCESS";
export const FETCH_SINGLE_GROUP_FAILED = "FETCH_SINGLE_GROUP_FAILED";

export const TOGGLE_LIST_ITEM_START = "TOGGLE_LIST_ITEM_START";
export const TOGGLE_LIST_ITEM_SUCCESS = "TOGGLE_LIST_ITEM_SUCCESS";
export const TOGGLE_LIST_ITEM_FAILED = "TOGGLE_LIST_ITEM_FAILED";
export const TOGGLE_LIST_ITEM_LOCAL = "TOGGLE_LIST_ITEM_LOCAL";

export const CREATE_NEW_GROUP_START = "CREATE_NEW_GROUP_START";
export const CREATE_NEW_GROUP_SUCCESS = "CREATE_NEW_GROUP_SUCCESS";
export const CREATE_NEW_GROUP_FAILED = "CREATE_NEW_GROUP_FAILED"

export const EDIT_GROUP_DATA_START = "EDIT_GROUP_DATA_START";
export const EDIT_GROUP_DATA_SUCCESS = "EDIT_GROUP_DATA_SUCCESS";
export const EDIT_GROUP_DATA_FAILED = "EDIT_GROUP_DATA_FAILED";

export const FETCH_INVITATION_LINK_START = "FETCH_INVITATION_LINK_START";
export const FETCH_INVITATION_LINK_SUCCESS = "FETCH_INVITATION_LINK_SUCCESS";
export const FETCH_INVITATION_LINK_FAILED = "FETCH_INVITATION_LINK_FAILED";

export const ACCEPT_OR_DECLINE_INVITATION_START = "ACCEPT_OR_DECLINE_INVITATION_START";
export const ACCEPT_OR_DECLINE_INVITATION_SUCCESS = "ACCEPT_OR_DECLINE_INVITATION_SUCCESS";
export const ACCEPT_OR_DECLINE_INVITATION_FAILED = "ACCEPT_OR_DECLINE_INVITATION_FAILED";

export const CREATE_GROUP_INVITATION_LINK_START = "CREATE_GROUP_INVITATION_LINK_START";
export const CREATE_GROUP_INVITATION_LINK_SUCCESS = "CREATE_GROUP_INVITATION_LINK_SUCCESS";
export const CREATE_GROUP_INVITATION_LINK_FAILED = "CREATE_GROUP_INVITATION_LINK_FAILED";
export const CREATE_GROUP_INVITATION_PERSONAL_SUCCESS = "CREATE_GROUP_INVITATION_PERSONAL_SUCCESS";

export const SEND_NOTIFICATION_START = "SEND_NOTIFICATION_START";
export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";
export const SEND_NOTIFICATION_FAILED = "SEND_NOTIFICATION_FAILED";

export const JOIN_PUBLIC_GROUP_NO_INVITATION_START = "JOIN_PUBLIC_GROUP_NO_INVITATION_START"
export const JOIN_PUBLIC_GROUP_NO_INVITATION_SUCCESS = "JOIN_PUBLIC_GROUP_NO_INVITATION_SUCCESS"
export const JOIN_PUBLIC_GROUP_NO_INVITATION_FAILED = "JOIN_PUBLIC_GROUP_NO_INVITATION_FAILED"

export const DELETE_GROUP_START = 'DELETE_GROUP_START';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILED = 'DELETE_GROUP_FAILED';

export const ADD_TASK_ITEM_START = "ADD_TASK_ITEM_START";
export const ADD_TASK_ITEM_SUCCESS = "ADD_TASK_ITEM_SUCCESS";
export const ADD_TASK_ITEM_FAILED = "ADD_TASK_ITEM_FAILED";

export const SUBMIT_PROFILE_CHANGES_START = "SUBMIT_PROFILE_CHANGES_START";
export const SUBMIT_PROFILE_CHANGES_SUCCESS = "SUBMIT_PROFILE_CHANGES_SUCCESS";
export const SUBMIT_PROFILE_CHANGES_FAILED = "SUBMIT_PROFILE_CHANGES_FAILED";

export const DELETE_TASK_ITEM_START = "DELETE_TASK_ITEM_START";
export const DELETE_TASK_ITEM_SUCCESS = "DELETE_TASK_ITEM_SUCCESS";
export const DELETE_TASK_ITEM_FAILED = "DELETE_TASK_ITEM_FAILED";

export const POST_NEW_MESSAGE_START = "POST_NEW_MESSAGE_START";
export const POST_NEW_MESSAGE_SUCCESS = "POST_NEW_MESSAGE_SUCCESS";
export const POST_NEW_MESSAGE_FAILED = "POST_NEW_MESSAGE_FAILED";

export const CLEAR_NOTIFICATION_START = "CLEAR_NOTIFICATION_START";
export const CLEAR_NOTIFICATION_SUCCESS = "CLEAR_NOTIFICATION_SUCCESS";
export const CLEAR_NOTIFICATION_FAILED = "CLEAR_NOTIFICATION_FAILED";

export const FINISH_FETCHING_INITIAL_DATA = "FINISH_FETCHING_INITIAL_DATA";

export const MESSAGE_OBSERVER_START = "MESSAGE_OBSERVER_START";
export const MESSAGE_OBSERVER_STOP = "MESSAGE_OBSERVER_STOP";
export const MESSAGE_UPDATE_RECEIVED = "MESSAGE_UPDATE_RECEIVED";

export const LEAVE_GROUP_START = "LEAVE_GROUP_START";
export const LEAVE_GROUP_SUCCESS = "LEAVE_GROUP_SUCCESS";
export const LEAVE_GROUP_FAILED = "FAILED_GROUP_FAILED";

//UI

export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const OPEN_SNACKBAR = "OPEN_SNACKBAR";